# Generated by Django 5.1.6 on 2025-04-04 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_iban', models.CharField(default='ES2222222222222222', max_length=100)),
                ('nombre_asterisco', models.CharField(default='nombre*', max_length=1222)),
                ('genero', models.CharField(choices=[('masculino', 'masculino'), ('femenino', 'femenino')], default='masculino', max_length=12)),
                ('created_at', models.DateField(default='2011-03-11')),
                ('fundraiser_name', models.CharField(default='2222', max_length=225)),
                ('fundraiser_code', models.BigIntegerField(default='11111')),
                ('saludo', models.CharField(choices=[('D.', 'Don'), ('Dña.', 'Doña')], default='D.', max_length=4)),
                ('primer_canal_captacion', models.CharField(default='F2F Boost Impact (Madrid)', max_length=100)),
                ('canal_entrada', models.CharField(default='F2F', max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('tipo_identificacion', models.CharField(choices=[('NIF', 'NIF'), ('NIE', 'NIE'), ('Pasaporte', 'Pasaporte'), ('CIF', 'CIF')], default='NIF', max_length=20)),
                ('numero_identificacion', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('via_principal', models.CharField(max_length=255)),
                ('cp_direccion', models.CharField(max_length=5)),
                ('ciudad_direccion', models.CharField(max_length=100)),
                ('estado_provincia', models.CharField(max_length=100)),
                ('recibe_memoria', models.CharField(default='SI', max_length=2)),
                ('recibe_correspondencia', models.CharField(default='SI', max_length=20)),
                ('movil', models.CharField(max_length=9)),
                ('telefono_casa', models.CharField(blank=True, max_length=9, null=True)),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('importe', models.CharField(default='2222222', max_length=40)),
                ('otra_cantidad', models.CharField(blank=True, default='2222222', max_length=40, null=True)),
                ('periodicidad', models.CharField(choices=[('Mensual', 'Mensual'), ('Trimestral', 'Trimestral'), ('Semestral', 'Semestral'), ('Anual', 'Anual')], default='Mensual', max_length=20)),
                ('dia_presentacion', models.CharField(default='0', max_length=222)),
                ('medio_pago', models.CharField(default='DOMICILIACIÓN', max_length=20)),
                ('tipo_pago', models.CharField(default='CUOTA', max_length=20)),
                ('concepto_recibo', models.CharField(default='GRACIAS POR TU AYUDA - Fundación Aladina', max_length=100)),
                ('mandato', models.TextField(blank=True, null=True)),
                ('nombre_autom', models.CharField(blank=True, max_length=255, null=True)),
                ('persona_id', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_socio', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_relacion', models.CharField(default='Socio', max_length=20)),
                ('fecha_alta', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True, verbose_name='notas')),
            ],
        ),
    ]
