# Generated by Django 5.1.6 on 2025-04-23 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0004_alter_formulario_ciudad_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='movil',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='telefono_casa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
