# Generated by Django 5.1.6 on 2025-03-05 00:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "formulario",
            "0005_formulario_created_at_formulario_fundraiser_code_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="formulario",
            name="genero",
            field=models.CharField(
                choices=[("masculino", "masculino"), ("femenino", "femenino")],
                default="masculino",
                max_length=12,
            ),
        ),
    ]
