# Generated by Django 5.1.6 on 2025-04-23 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0005_alter_formulario_movil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='apellidos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='canal_entrada',
            field=models.CharField(blank=True, default='F2F', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='concepto_recibo',
            field=models.CharField(blank=True, default='GRACIAS POR TU AYUDA - Fundación Aladina', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='created_at',
            field=models.DateField(blank=True, default='2011-03-11', null=True),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='dia_presentacion',
            field=models.CharField(blank=True, default='0', max_length=222, null=True),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='fundraiser_code',
            field=models.BigIntegerField(blank=True, default='11111', null=True),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='fundraiser_name',
            field=models.CharField(blank=True, default='2222', max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='genero',
            field=models.CharField(blank=True, choices=[('masculino', 'masculino'), ('femenino', 'femenino')], default='masculino', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='medio_pago',
            field=models.CharField(blank=True, default='DOMICILIACIÓN', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='no_iban',
            field=models.CharField(blank=True, default='ES2222222222222222', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='nombre_asterisco',
            field=models.CharField(blank=True, default='nombre*', max_length=1222, null=True),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='periodicidad',
            field=models.CharField(blank=True, choices=[('Mensual', 'Mensual'), ('Trimestral', 'Trimestral'), ('Semestral', 'Semestral'), ('Anual', 'Anual')], default='Mensual', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='primer_canal_captacion',
            field=models.CharField(blank=True, default='F2F Boost Impact (Madrid)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='saludo',
            field=models.CharField(blank=True, choices=[('D.', 'Don'), ('Dña.', 'Doña')], default='D.', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='tipo_identificacion',
            field=models.CharField(blank=True, choices=[('NIF', 'NIF'), ('NIE', 'NIE'), ('Pasaporte', 'Pasaporte'), ('CIF', 'CIF')], default='NIF', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='tipo_pago',
            field=models.CharField(blank=True, default='CUOTA', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='tipo_relacion',
            field=models.CharField(blank=True, default='Socio', max_length=20, null=True),
        ),
    ]
