# Generated by Django 5.1.6 on 2025-04-23 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0006_alter_formulario_apellidos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='fundraiser_code',
            field=models.CharField(blank=True, default='2222', max_length=225, null=True),
        ),
    ]
