# Generated by Django 5.1.6 on 2025-03-05 00:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formulario", "0006_formulario_genero"),
    ]

    operations = [
        migrations.AddField(
            model_name="formulario",
            name="no_iban",
            field=models.CharField(default="ES2222222222222222", max_length=100),
        ),
    ]
