# Generated by Django 5.1.6 on 2025-03-05 01:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formulario", "0007_formulario_no_iban"),
    ]

    operations = [
        migrations.AddField(
            model_name="formulario",
            name="nombre_asterisco",
            field=models.CharField(default="nombre*", max_length=1222),
        ),
    ]
