# Generated by Django 5.1.6 on 2025-03-05 01:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formulario", "0009_remove_formulario_numero_cuenta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formulario",
            name="dia_presentacion",
            field=models.CharField(default="0", max_length=222),
        ),
    ]
