# Generated by Django 5.1.6 on 2025-03-11 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0010_alter_formulario_dia_presentacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulario',
            name='fecha_primer_pago',
        ),
    ]
