# Generated by Django 5.1.6 on 2025-04-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areaPrivada', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fundRaiserCode',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
