# Generated by Django 5.1.6 on 2025-04-11 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areaPrivada', '0002_user_fundraisercode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_socio', models.CharField(max_length=100)),
                ('apellido_socio', models.CharField(max_length=100)),
                ('genero_socio', models.CharField(max_length=10)),
                ('tipo_identificacion_socio', models.CharField(max_length=20)),
                ('numero_identificacion_socio', models.CharField(max_length=20, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('via_principal', models.CharField(max_length=255)),
                ('cp_direccion', models.CharField(max_length=10)),
                ('ciudad_direccion', models.CharField(max_length=100)),
                ('estado_provincia', models.CharField(max_length=100)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('periodicidad', models.CharField(max_length=20)),
                ('dia_presentacion', models.PositiveSmallIntegerField(default=1)),
                ('medio_pago', models.CharField(max_length=20)),
                ('tipo_pago', models.CharField(max_length=20)),
                ('primer_canal_captacion', models.CharField(max_length=100)),
                ('canal_entrada', models.CharField(max_length=50)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('fundraiser', models.ForeignKey(blank=True, limit_choices_to={'role': 'COMERCIAL'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='socios_captados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Socio',
                'verbose_name_plural': 'Socios',
                'ordering': ['-fecha_alta'],
                'indexes': [models.Index(fields=['numero_identificacion_socio'], name='areaPrivada_numero__2bb604_idx'), models.Index(fields=['fundraiser'], name='areaPrivada_fundrai_e0a369_idx'), models.Index(fields=['fecha_alta'], name='areaPrivada_fecha_a_ba516e_idx')],
            },
        ),
    ]
