# Generated by Django 5.1.6 on 2025-04-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areaPrivada', '0002_fundraiser'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='is_borrador',
            field=models.BooleanField(default=False),
        ),
    ]
