# Generated by Django 5.1.6 on 2025-04-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areaPrivada', '0003_socio_is_borrador'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='no_iban',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
