# Generated by Django 5.1.6 on 2025-04-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areaPrivada', '0003_socio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='dia_presentacion',
            field=models.CharField(default='1', max_length=255),
        ),
    ]
