# Generated by Django 5.1.6 on 2025-04-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areaPrivada', '0004_alter_socio_dia_presentacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='status',
            field=models.CharField(default='Pendiente', max_length=255),
        ),
    ]
