# Generated by Django 5.1.6 on 2025-04-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areaPrivada', '0004_socio_no_iban'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='email_socio',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='socio',
            name='telefono_socio',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='socio',
            name='numero_identificacion_socio',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='socio',
            name='tipo_identificacion_socio',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
