# Generated by Django 5.1.6 on 2025-04-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areaPrivada', '0005_socio_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='devolucion',
            field=models.BooleanField(default=False),
        ),
    ]
