# Generated by Django 5.1.6 on 2025-04-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areaPrivada', '0005_socio_email_socio_socio_telefono_socio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='fecha_alta_real',
            field=models.DateField(blank=True, null=True),
        ),
    ]
