# Generated by Django 5.1.6 on 2025-04-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areaPrivada', '0006_socio_fecha_alta_real'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrollamada',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
