# Generated by Django 5.1.6 on 2025-04-11 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areaPrivada', '0006_socio_devolucion'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='no_llamadas',
            field=models.IntegerField(default=0),
        ),
    ]
