# Generated by Django 5.1.6 on 2025-04-11 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areaPrivada', '0007_socio_no_llamadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='fecha_verificacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
