# Generated by Django 5.1.6 on 2025-09-06 20:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "areaPrivada",
            "0008_alter_socio_apellido_socio_alter_socio_canal_entrada_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTrazability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("view_name", models.CharField(max_length=255)),
                ("url_path", models.CharField(max_length=500)),
                ("entry_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("exit_time", models.DateTimeField(blank=True, null=True)),
                ("duration", models.DurationField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("device_type", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "browser_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "browser_version",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("os_name", models.CharField(blank=True, max_length=100, null=True)),
                ("os_version", models.CharField(blank=True, max_length=50, null=True)),
                ("is_bot", models.BooleanField(default=False)),
                (
                    "device_model",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trazability_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User Trazability Logs",
                "ordering": ["-entry_time"],
            },
        ),
    ]
