# Generated by Django 5.1.6 on 2025-04-15 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areaPrivada', '0008_socio_fecha_creacion_socio_fecha_verificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroLlamada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_llamada', models.IntegerField(default=1)),
                ('resultado', models.CharField(max_length=100)),
                ('notas', models.TextField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('fundraiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areaPrivada.socio')),
            ],
        ),
    ]
