# Generated by Django 5.1.6 on 2025-04-20 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areaPrivada', '0009_registrollamada'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
