# Generated by Django 5.1.6 on 2025-04-21 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areaPrivada', '0010_socio_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='numero_identificacion_socio',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('GESTOR', 'Gestor'), ('JEFE', 'Jefe'), ('COMERCIAL', 'Comercial'), ('USER', 'Usuario')], default='USER', max_length=50),
        ),
    ]
