# Generated by Django 5.1.6 on 2025-03-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Formulario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "saludo",
                    models.CharField(
                        choices=[("D.", "Don"), ("Dña.", "Doña")],
                        default="D.",
                        max_length=4,
                    ),
                ),
                (
                    "primer_canal_captacion",
                    models.CharField(
                        default="F2F Boost Impact (Madrid)", max_length=100
                    ),
                ),
                ("canal_entrada", models.CharField(default="F2F", max_length=10)),
                ("nombre", models.CharField(max_length=100)),
                ("apellidos", models.CharField(max_length=100)),
                (
                    "tipo_identificacion",
                    models.CharField(
                        choices=[
                            ("NIF", "NIF"),
                            ("NIE", "NIE"),
                            ("Pasaporte", "Pasaporte"),
                        ],
                        default="NIF",
                        max_length=20,
                    ),
                ),
                ("numero_identificacion", models.CharField(max_length=20)),
                ("fecha_nacimiento", models.DateField()),
                ("via_principal", models.CharField(max_length=255)),
                ("cp_direccion", models.CharField(max_length=10)),
                ("ciudad_direccion", models.CharField(max_length=100)),
                ("estado_provincia", models.CharField(max_length=100)),
                ("recibe_memoria", models.CharField(default="SI", max_length=2)),
                ("recibe_correspondencia", models.BooleanField(default=True)),
                ("movil", models.CharField(max_length=20)),
                (
                    "telefono_casa",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("correo_electronico", models.EmailField(max_length=254)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "importe",
                    models.CharField(
                        choices=[
                            ("10", "10€"),
                            ("20", "20€"),
                            ("30", "30€"),
                            ("50", "50€"),
                            ("otra", "Otra Cantidad"),
                        ],
                        default="otra",
                        max_length=10,
                    ),
                ),
                (
                    "otra_cantidad",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "periodicidad",
                    models.CharField(
                        choices=[
                            ("Mensual", "Mensual"),
                            ("Trimestral", "Trimestral"),
                            ("Semestral", "Semestral"),
                            ("Anual", "Anual"),
                        ],
                        default="Mensual",
                        max_length=20,
                    ),
                ),
                ("fecha_primer_pago", models.DateField(blank=True, null=True)),
                ("dia_presentacion", models.IntegerField(default=0)),
                (
                    "medio_pago",
                    models.CharField(default="DOMICILIACIÓN", max_length=20),
                ),
                ("tipo_pago", models.CharField(default="CUOTA", max_length=20)),
                ("numero_cuenta", models.CharField(default="0", max_length=34)),
                (
                    "concepto_recibo",
                    models.CharField(
                        default="GRACIAS POR TU AYUDA - Fundación Aladina",
                        max_length=100,
                    ),
                ),
                ("mandato", models.TextField(blank=True, null=True)),
                (
                    "nombre_autom",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("persona_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "nombre_socio",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("tipo_relacion", models.CharField(default="Socio", max_length=20)),
                ("fecha_alta", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
