# Generated by Django 5.1.6 on 2025-03-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formulario", "0002_alter_formulario_recibe_correspondencia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formulario",
            name="recibe_correspondencia",
            field=models.CharField(default="SI", max_length=20),
        ),
    ]
