# Generated by Django 5.1.6 on 2025-03-04 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formulario", "0003_alter_formulario_recibe_correspondencia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formulario",
            name="importe",
            field=models.CharField(
                choices=[
                    ("10€", "10€"),
                    ("20€", "20€"),
                    ("30€", "30€"),
                    ("50€", "50€"),
                    ("Otra Cantidad", "Otra Cantidad"),
                ],
                default="Otra Cantidad",
                max_length=20,
            ),
        ),
    ]
