# Generated by Django 5.1.6 on 2025-03-04 23:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formulario", "0004_alter_formulario_importe"),
    ]

    operations = [
        migrations.AddField(
            model_name="formulario",
            name="created_at",
            field=models.DateField(default="2011-03-11"),
        ),
        migrations.AddField(
            model_name="formulario",
            name="fundraiser_code",
            field=models.IntegerField(default="11111"),
        ),
        migrations.AddField(
            model_name="formulario",
            name="fundraiser_name",
            field=models.CharField(default="2222", max_length=225),
        ),
    ]
